source "https://rubygems.org"

gem "rails", "5.0.0.beta3"

gem "puma"
gem "sass-rails", "~> 5.0"
gem "uglifier", ">= 1.3.0"

gem "turbolinks", "~> 5.x"
gem "jquery-rails"

gem "i18n-js", path: "../.."

# You can use any package manager (bower, npm, webpack).
# I"m using rails-assets for simplicity.
source "https://rails-assets.org" do
  gem "rails-assets-almond"
end

group :development, :test do
  gem "pry-meta", require: false
end

group :development do
  gem "listen"
end
